a=float(input("Digite um número: "))
b=float(input("Digite um número: "))
c=float(input("Digite um número: "))
d=float(input("Digite um número: "))
e=float(input("Digite um número: "))
print((a+b+c+d+e)/5)
